### ISSUE TITLE
Тестирование версии 2.0.0

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/week-planner-for-marusia#105]
[Задачи](https://github.com/Valentina810/week-planner-for-marusia/issues?q=is%3Aclosed+label%3A2.0.0)
[Образ для тестирования](https://hub.docker.com/r/valentinakole/week-planner-for-marusia/tags)
[Инструкция как локально развернуть сервис в докере](https://github.com/T-1000-bots/work-rules/blob/main/instructions/how-to-deploy-an-image-locally-in-docker.md) , напоминаю что сваггер недоступен при запущенном сервисе после доработки с обработкой только post-запросов
[Инструкция как смотреть логи контейнера](https://github.com/T-1000-bots/work-rules/blob/main/instructions/how-to-view-logs-of-a-running-docker-container.md)

**Что проверить:**
- [x] Все фичи - что поправлено/добавлено то, что нужно было в задаче [список](https://github.com/Valentina810/week-planner-for-marusia/issues?q=is%3Aclosed+label%3A2.0.0). Можешь завести подзадачки, если нужно, как тебе удобнее.
- [x] Регресс, чтобы то, что раньше работало не сломалось. Как раз пригодится постман-коллекция которую ты делала раньше.
- [x] Нагрузка пока не нужна, сделаем как опубликуем.

На всё про всё - месяц (примерно до 1 декабря). Вопросы/баги - заводи задачками на меня, чтобы ничего не потерялось.

**Comment by kate-polik** [comment]
Список задач:
1. https://github.com/Valentina810/week-planner-for-marusia/issues/106

**Comment by Valentina810** [comment]
@kate-polik проверь плиз еще если нет в регрессе кейс, когда в персистентном хранилище приходит какой-нибудь другой объект, json корректный, но не объект сам не том, который ожидает навык. Должен быть корректный ответ, а не завал

**Comment by kate-polik** [comment]
❗В рамках задачи также 
проверить: https://github.com/Valentina810/week-planner-for-marusia/issues/105#issuecomment-2436429495
+
доделать: https://github.com/Valentina810/week-planner-for-marusia/pull/95#issuecomment-2295311349

**Comment by kate-polik** [comment]
Спасибо за подробный [коммент](https://github.com/Valentina810/week-planner-for-marusia/issues/105#issuecomment-2436429495)!
Вот какие результаты:
1.  Отправила рандомные значения в _state_ -> _session_ и в _state_ -> _user_
```json
    "state": {
        "session": {
            "id": 1,
            "name": "Alice",
            "age": 30,
            "city": "Moscow",
            "is_student": false
        },
        "user": {
            "id": 2,
            "name": "Bob",
            "age": 25,
            "city": "Saint Petersburg",
            "is_student": true
        }
    },
```
<details>
<summary>Пример запроса целиком</summary>

```json
{
    "meta": {
        "timezone": "Europe/Moscow"
    },
    "request": {
        "command": "запусти skill планировщик недели"
    },
    "session": {
        "user_id": "{{user_id}}",
        "session_id": "{{session_id}}",
        "message_id": 0
    },
    "state": {
        "session": {
            "id": 1,
            "name": "Alice",
            "age": 30,
            "city": "Moscow",
            "is_student": false
        },
        "user": {
            "id": 2,
            "name": "Bob",
            "age": 25,
            "city": "Saint Petersburg",
            "is_student": true
        }
    },
    "version": "2.0.0"
}
```

</details> 

Получила 200 ОК ответ, соответствующий команде ("command"), при этом в ответе  "session_state": {} пришел пустой, "user_state_update" отсутствует

<details>
<summary>Пример ответа целиком</summary>

```json
{
    "response": {
        "text": "Вас приветствует навык \"Планировщик недели\"! Навык предоставляет возможность составить план событий на неделю, начиная с сегодняшнего дня. Для добавления событий в расписание скажите \"Добавь событие\", далее следуйте инструкциям. Если вы хотите узнать план событий на сегодня скажите \"План на сегодня\". Для того чтобы узнать план на завтра, воспользуйтесь командой \"План на завтра\". Можно узнать план на всю неделю с помощью команды \"План на неделю\". Для выхода из навыка скажите \"Выход\". Если у вас остались вопросы, скажите \"Справка\" для подробного объяснения работы навыка",
        "tts": "Вас приветствует навык \"Планировщик недели\"! Навык предоставляет возможность составить план событий на неделю, начиная с сегодняшнего дня. Для добавления событий в расписание скажите \"Добавь событие\", далее следуйте инструкциям. Если вы хотите узнать план событий на сегодня скажите \"План на сегодня\". Для того чтобы узнать план на завтра, воспользуйтесь командой \"План на завтра\". Можно узнать план на всю неделю с помощью команды \"План на неделю\". Для выхода из навыка скажите \"Выход\". Если у вас остались вопросы, скажите \"Справка\" для подробного объяснения работы навыка",
        "end_session": false
    },
    "session": {
        "user_id": "b4fde534",
        "session_id": "ffb392fd",
        "message_id": 0
    },
    "version": "2.0.0",
    "session_state": {}
}

```

</details> 
----------------------------------------------------------------------------------------------------------------------------

2. Отправила рандомные значения в _state_ -> _session_
```json
  "state": {
        "session": {
            "privet": "Как дела?"
        },
        "user": {}
    }
```
Получила 200 ОК ответ, соответствующий команде ("command"), при этом в ответе  "session_state": {} пришел пустой, "user_state_update" отсутствует

----------------------------------------------------------------------------------------------------------------------------

3. Отправила рандомные значения в _state_ -> _user_
```json
   "state": {
        "session": {},
        "user": {
            "privet": "Как дела?"
        }
    }
```
Получила 200 ОК ответ, соответствующий команде ("command"), при этом в ответе  "session_state" и "user_state_update" отсутствуют

Похоже на корректное поведение, @Valentina810, при  указании рандомных значений в , получаем корректные ответы, при этом:
- _user_state_update_ не приходит в ответе, когда ему получается нечего обновлять? 
- а _session_state_ пустой в ответах, так как нет нужного содержимого для записи предыдущий действий?

**Comment by Valentina810** [comment]
@kate-polik да, такое поведение и должно быть правильным. То что в контексте сессии мы затираем всё что нам не нужно - это да, нормально. Но вот конечно в контексте пользователя - не очень, так как могут хранить чот-то и другие навыки. Но для простоты реализации это пока было опущено. В идеале если что-то в контексте пользователя лежит, мы не должны это потирать, должны сохранить+добавить к этому своё ну или своё можем хранить где-то ещё, например в своей базе. Но это не реализовано, пока полностью убираем то, что нам не нужно.
Если эти поля приходят в ответах пустые, значит данных никаких нет, если полей нету, то это эквивалентно тому что они пришли со значением null

**Comment by kate-polik** [comment]
Итоговый список тест-кейсов, которые надо доработать/добавить в коллекции и что нужно доделать в Postman :

- [ ] 1. приветственное сообщение навыка содержит подробный рассказ о его функциях и командах, добавить в справку инфу о версии
- [ ] 2. возврат даты, вместо 24-06-2024 возвращать понедельник, 24 июня, без года
- [ ] если часы во времени содержат ноль впереди, то убрать ноль #102
- [ ] 3. некорректный user-agent, то возвращается SC_UNSUPPORTED_MEDIA_TYPE = 415, 
- [ ] 4. метод не POST, то возвращается SC_METHOD_NOT_ALLOWED = 405.
- [ ] 5. некорректный user-agent + метод не POST, то возвращается SC_UNSUPPORTED_MEDIA_TYPE = 415
- [ ] 6. указания времени события для значений: "Полдень" 
- [ ] 7. указания времени события для значений: "Полночь"
- [ ] 8. рандомные значения в state -> session и в state -> user => 200 ОК ответ, соответствующий команде ("command"), при этом в ответе "session_state": {} пришел пустой, "user_state_update" отсутствует
- [ ] 9. рандомные значения в state -> session => 200 ОК ответ, соответствующий команде ("command"), при этом в ответе "session_state": {} пришел пустой, "user_state_update" отсутствует
- [ ] 10. рандомные значения в state -> user => Получила 200 ОК ответ, соответствующий команде ("command"), при этом в ответе "session_state" и "user_state_update" отсутствуют
- [ ] 11. При проверке плана на неделю включить тест с большИм количеством событий (хотя бы каждый день по 3 события), аналогично проверке 4.4 PLAN_tom_list, только для плана на неделю и чтобы у событий были более длинные названия (от 10 до 200-300 символов)
- [ ]  12. добавление события на сегодня когда сегодня разные даты для разных таймзон - события должны добавляться на правильное число. Например, сегодня в Москве понедельник, а в Австралии уже вторник. Пользователь из Австралии добавляет событие на понедельник. Событие должно быть добавлено на следующий понедельник. Для пользователя из Москвы - на текущий понедельник, так как он еще не прошел.
- [ ]  13. озвучивание плана для пользователя из Австралии/Москвы на завтра (когда даты завтра - разные)
- [ ]  14. озвучивание плана для пользователя из Австралии/Москвы на сегодня (когда даты сегодня - разные)
- [ ]  15. при messageId=0 у нас также должны удаляться соответствующие события: все, которые были ранее сегодняшнего дня
- [ ] 16. Добавить в описание проекта Postman пункты 1 - 15 и в каких запросах они проверяются
- [ ] 17. удалить старую коллекцию
- [ ] 18. дублирующиеся в проверках функции вынести на уровень выше, и в проверках просто их переиспользовать

**Comment by Valentina810** [comment]
@kate-polik  да, нормально

**Comment by kate-polik** [comment]
Основное тестирование по обновлениям версии 2.0.0 завершено.
Требуется доработка проекта Postman согласно оставшимся пунктам https://github.com/Valentina810/week-planner-for-marusia/issues/105#issuecomment-2505174137, проект пока в работе (есть не настроенные ассерты и черновые названия запросов), ориентировочные сроки 8.12, резервная копия залита во [временную ветку](https://github.com/Valentina810/week-planner-for-marusia/blob/temp-postman-project/src/postman/Marusia_API_2.0.0.postman_collection.json)
