### ISSUE TITLE
#81, #88, #97_Тест_Добавить фильтр входящих запросов по заголовку 'user-agent: MailRu-VC/1.0'

### ISSUE THREAD

**Issue by kate-polik** [Valentina810/week-planner-for-marusia#111]
Родительская задача 
https://github.com/Valentina810/week-planner-for-marusia/issues/105

Задачи с требованиями: 
https://github.com/Valentina810/week-planner-for-marusia/issues/81 
https://github.com/Valentina810/week-planner-for-marusia/issues/88
https://github.com/Valentina810/week-planner-for-marusia/issues/97

**Comment by kate-polik** [comment]
1. Уточнить текст ошибки:
![Image](https://github.com/user-attachments/assets/b4ae08b0-5304-4d3c-9a7e-c4f9e2d53e96)

2. Уточнить содержимое лога в случае ошибки:
![Image](https://github.com/user-attachments/assets/4c233d25-f987-4d07-9345-e467856c4253)

3.  Проверки: метод не Post, отсутствие/отличие от значения заголовка "user_agent=MailRu-VC/1.0"

**Comment by Valentina810** [comment]
Если некорректный user-agent, то возвращаается SC_UNSUPPORTED_MEDIA_TYPE = 415
если метод не POST, то SC_METHOD_NOT_ALLOWED = 405.
Содержимое лога - если ты имеешь ввиду логировать тело ответа с ошибкой, то нет, в таком случае не логируется, просто сообщение о том, что дальше запрос не прокидывался

**Comment by kate-polik** [comment]
> * 81 - была вынесена в отдельную библиотеку функция преобразования запроса в курл
> * 97 - небольшие правки в readme, поднята версия java при сборке в докере до 21, добавлены в докер-файл переменные с помощью которых прокидываются креды для гитхаба (для подключения библиотеки преобразования запроса в курл)

@Valentina810 подскажи, пожалуйста, надо ли это как-то протестить?


> 3\. Проверить вместе оба условия

получаю статус 415, получается некорректный user-agent приоритетнее?

**Comment by Valentina810** [comment]
@kate-polik реализация такая
```java
    private static int determineResponseCode(HttpServletRequest request) {
        boolean isUserAgentValid = REQUIRED_USER_AGENT.equals(request.getHeader(USER_AGENT_HEADER));
        boolean isMethodSupported = SUPPORTED_METHOD.equalsIgnoreCase(request.getMethod());

        return !isUserAgentValid ? SC_UNSUPPORTED_MEDIA_TYPE :
                !isMethodSupported ? SC_METHOD_NOT_ALLOWED : 0;
    }
```
то есть если уже невалидный USER_AGENT_HEADER дальше не проверяем, выкидываем 415

**Comment by kate-polik** [comment]
Текущее поведение соответствует ожидаемому см. комментарии выше, начиная с https://github.com/Valentina810/week-planner-for-marusia/issues/111#issuecomment-2477884046
