### ISSUE TITLE
#90_Тест_Проверка корректной обработки события в зависимости от часового пояса

### ISSUE THREAD

**Issue by kate-polik** [Valentina810/week-planner-for-marusia#114]
Родительская задача https://github.com/Valentina810/week-planner-for-marusia/issues/105
Задача с требованиями https://github.com/Valentina810/week-planner-for-marusia/issues/90, https://github.com/Valentina810/week-planner-for-marusia/pull/103

**Comment by Valentina810** [comment]
@kate-polik тут [кейсы](https://github.com/Valentina810/week-planner-for-marusia/issues/90#issuecomment-2397642413)

**Comment by kate-polik** [comment]
Реализация корректна
