### ISSUE TITLE
Тестирование

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/week-planner-for-marusia#59]
Сделать коллекцию в постман

**Comment by Valentina810** [comment]
Нужно будет декомпозировать, задача большая, примерные шаги:
- [ ] изучить доку, задать по ней вопросы
- [ ] возможно нужно будет внести правки в документацию
- [ ] сделать чек-лист
- [ ] отдать чек-лист на ревью
- [ ] по чек-листу сделать коллекцию
- [ ] разобраться как её прикрутить через newman https://www.youtube.com/watch?v=f2gGCO_L318
- [ ] настроить автозапуск по коммиту в main

**Comment by Valentina810** [comment]
Инструкция как смотреть логи докер-контейнера на сервере https://github.com/T-1000-bots/work-rules/blob/main/how-to-view-logs-of-a-running-docker-container.md

**Comment by kate-polik** [comment]
Декомпозиция главной задачи:

- [ ] https://github.com/Valentina810/week-planner-for-marusia/issues/66
- [ ] https://github.com/Valentina810/week-planner-for-marusia/issues/67
- [ ] https://github.com/Valentina810/week-planner-for-marusia/issues/68
- [ ] https://github.com/Valentina810/week-planner-for-marusia/issues/69
- [ ] https://github.com/Valentina810/week-planner-for-marusia/issues/70

**Comment by kate-polik** [comment]
Хотелось бы обсудить следующие вопросы:
1. как формируется "end_session": true в ответе, исходя в "command": "выход" в запросе?
2. Должны ли сортироваться события в ответе в  "user_state_update" ->   "week" -> "days" ? Сейчас работает так: 
![image](https://github.com/user-attachments/assets/ae03e7c7-28f4-407d-ad48-696ab40ffc2e)
пример запроса в коллекции: 6.1  WEEKLY_PLAN_not_empty_mi1
`Запрос отрывок  
	   
	   "user": {
            "week": {
                "days": {
                     "30-10-2024": [
                        {
                            "time": "15:00",
                            "name": "Прогулка на берегу моря"
                        },
                        {
                            "time": "09:00",
                            "name": "Поздний обед"
                        }
                    ],
                    "03-05-2024": [
                        {
                            "time": "20:00",
                            "name": "Ужин"
                        },
                        {
                            "time": "17:00",
                            "name": "Велосипедная прогулка"
                        }
                    ],
                    "01-08-2024": [
                        {
                            "time": "17:00",
                            "name": "Ужин"
                        },
                        {
                            "time": "17:01",
                            "name": "Велосипедная прогулка"
                        }
                    ]
                   
                }
            }
		}
`
3.  Влияет ли на что-то параметр в запросе "message_id"?  Может ли указывать рандомно или лучше четко инкрементировать?
![image](https://github.com/user-attachments/assets/5a59f07d-a391-4027-b5b7-dd2033142403)
4.  Отсутствует валидация на ввод значений, например, на шагах "ADD_DAY",  "ADD_TIME" принимаются любые значения, в итоге получаем событие на текущую дату на 00:00
5.  В коллекции есть тестовый запрос, где есть большой список событий, я проверяю в ответе только первое и последнее значение для соответствующий событий, подойдет ли такая проверка?

@Valentina810 Будет ли удобно обсудить голосом и когда или лучше письменно? 

-----------------------------------------------------------------------------------------------------------------------
Не забыть:
Провести повторную нагрузку после обновления версии, внести правки в проект: расклонировать коллекции с уникальными параметрами, чтобы можно было запускать по кнопке без внесения параментров вручную, добавить это описание в доку

**Comment by kate-polik** [comment]
Ожидаю ответа по https://github.com/Valentina810/week-planner-for-marusia/pull/95

**Comment by Valentina810** [comment]
@kate-polik  по ньюману пока задачу не делаем (последние два шага чек-листа). Вернемся к этому вопросу позже

**Comment by Valentina810** [comment]
@kate-polik ПР просмотрела
