### ISSUE TITLE
Добавить фильтр входящих запросов по заголовку 'user-agent: MailRu-VC/1.0'

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/week-planner-for-marusia#81]
+ Блокировки/фильтры:  

**IP: 74.82.47.5**:
curl -X GET 'https://IP/' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/api/v2/static/not.found' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/remote/logincheck' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/geoserver/web/' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0'  -H 'accept: */*'  -H 'accept-encoding: gzip'

**IP: 45.156.128.47**
curl -X GET 'https://IP/' -H 'host: IP  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/aspera/faspex/' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip' 

**IP: 209.170.91.200**
curl -X GET 'https://IP/' -H 'host: IP'  -H 'connection: keep-alive'  -H 'pragma: no-cache'  -H 'cache-control: no-cache'  -H 'sec-ch-ua: "Chromium";v="124", "HeadlessChrome";v="124", "Not-A.Brand";v="99"'  -H 'sec-ch-ua-mobile: ?0'  -H 'sec-ch-ua-platform: "Linux"'  -H 'upgrade-insecure-requests: 1'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36'  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'  -H 'sec-fetch-site: none'  -H 'sec-fetch-mode: navigate'  -H 'sec-fetch-user: ?1'  -H 'sec-fetch-dest: document'  -H 'accept-encoding: gzip, deflate, br'

**IP: 137.184.154.43**
curl -X GET 'https://payments.russo-para-brasileiros.space/' -H 'host: payments.russo-para-brasileiros.space'  -H 'accept-encoding: gzip, deflate'  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'  -H 'accept-language: en-US,en;q=0.9'  -H 'pragma: no-cache'  -H 'cache-control: no-cache'  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

**IP: 52.160.33.173**
curl -X GET 'https://IP/owa/auth/logon.aspx' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 zgrab/0.x'  -H 'accept: */*'  -H 'accept-encoding: gzip'

**IP: 80.82.77.202**
curl -X GET 'https://IP/aaa9' -H 'host: IP:443'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'  -H 'accept-encoding: gzip'  -H 'connection: close'

curl -X GET 'https://IP/aab9' -H 'host: IP:443'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'  -H 'accept-encoding: gzip'  -H 'connection: close'

**IP: 66.249.72.130**
curl -X GET 'https://IP/robots.txt' -H 'host: IP'  -H 'connection: keep-alive'  -H 'accept: text/plain,text/html,*/*'  -H 'user-agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'  -H 'accept-encoding: gzip, deflate, br'

**IP: 66.249.72.131**
curl -X GET 'https://IP/zabolevaniya-sosudov/varikoz/kak-prinimat-askorutin-pri-varikoze.html' -H 'host: IP'  -H 'amp-cache-transform: google;v="1..8"'  -H 'connection: keep-alive'  -H 'accept: text/html,application/xhtml+xml,application/signed-exchange;v=b3,application/xml;q=0.9,*/*;q=0.8'  -H 'from: googlebot(at)googlebot.com'  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.175 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'  -H 'accept-encoding: gzip, deflate, br'

curl -X GET 'https://IP/sustavy-i-kosti/simptomy-i-lechenie-osteoxondroza-tazobedrennyx-sustavov.html' -H 'host: IP'  -H 'amp-cache-transform: google;v="1..8"'  -H 'connection: keep-alive'  -H 'accept: text/html,application/xhtml+xml,application/signed-exchange;v=b3,application/xml;q=0.9,*/*;q=0.8'  -H 'from: googlebot(at)googlebot.com'  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.175 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'  -H 'accept-encoding: gzip, deflate, br'

curl -X GET 'https://IP/o-nogax/krasivye-i-strojnye-nozhki-domashnix-usloviyax.html' -H 'host: IP'  -H 'amp-cache-transform: google;v="1..8"'  -H 'connection: keep-alive'  -H 'accept: text/html,application/xhtml+xml,application/signed-exchange;v=b3,application/xml;q=0.9,*/*;q=0.8'  -H 'from: googlebot(at)googlebot.com'  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.175 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'  -H 'accept-encoding: gzip, deflate, br'

**IP: 103.14.26.206**
curl -X GET 'https://IP/restore.php' -H 'accept: */*'  -H 'host: IP'

**IP: 178.128.201.149**
curl -X OPTIONS 'https://localhost/'

curl -X GET 'https://localhost/nice%20ports%2C/Tri%6Eity.txt%2ebak'

**IP: 45.156.129.54**
curl -X GET 'https://IP/wp-content/plugins/wp-central/readme.txt' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip'

**IP: 178.128.201.149**
curl -X POST 'https://IP/sdk' -H 'content-length: 441'  -H 'user-agent: Mozilla/5.0 (compatible; Odin; https://docs.getodin.com/)'  -H 'host: IP'  -H 'connection: close' --data '<soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><operationID>00000001-00000001</operationID></soap:Header><soap:Body><RetrieveServiceContent xmlns="urn:internalvim25"><_this xsi:type="ManagedObjectReference" type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent></soap:Body></soap:Envelope>'

curl -X GET 'https://IP/odinhttpcall1719746830' -H 'user-agent: Mozilla/5.0 (compatible; Odin; https://docs.getodin.com/)'  -H 'host: IP'  -H 'connection: close'

curl -X GET 'https://IP/HNAP1' -H 'user-agent: Mozilla/5.0 (compatible; Odin; https://docs.getodin.com/)'  -H 'host: IP'  -H 'connection: close'

curl -X GET 'https://IP/evox/about' -H 'user-agent: Mozilla/5.0 (compatible; Odin; https://docs.getodin.com/)'  -H 'host: IP'  -H 'connection: close'

curl -X GET 'https://localhost/'

**IP: 68.183.68.79**
curl -X POST 'https://IP/' -H 'host: IP'  -H 'user-agent: Go-http-client/1.1'  -H 'connection: close'  -H 'content-length: 475'  -H 'x-aggregate-auth: 1' --data '<?xml version="1.0" encoding="UTF-8"?>
				<config-auth client="vpn" type="init" aggregate-auth-version="2">
				<version who="vpn">3.1.05160</version>
				<device-id device-type="iPhone13,1" platform-version="15.0.1" unique-id="ABCDEF1234567890">iOS</device-id>
				<mac-address-list>
					<mac-address>01:23:45:67:89:AB</mac-address>
				</mac-address-list>
				<group-select>VPN</group-select>
				<group-access>https://IP:443</group-access>
				</config-auth>'

**IP: 57.151.70.180**
curl -X GET 'https://IP/version' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 zgrab/0.x'  -H 'accept: */*'  -H 'accept-encoding: gzip'

**IP: 66.240.192.138**
curl -X GET 'https://IP/robots.txt' -H 'host: IP'  -H 'accept-encoding: identity'

curl -X GET 'https://IP/sitemap.xml' -H 'host: IP'

curl -X GET 'https://IP/.well-known/security.txt' -H 'host: IP'  -H 'accept-encoding: identity'

curl -X GET 'https://IP/favicon.ico' -H 'host: IP'  -H 'connection: keep-alive'  -H 'accept-encoding: gzip, deflate'  -H 'accept: */*'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36'

**IP: 78.153.140.177**
curl -X GET 'https://IP/.env' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36'  -H 'accept-encoding: gzip, deflate'  -H 'accept: */*'  -H 'connection: keep-alive'

**IP: 167.172.120.3**
curl -X GET 'https://IP/ab2g' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 zgrab/0.x'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://1IP/ab2h' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 zgrab/0.x'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/alive.php' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/t4' -H 'host: IP'  -H 'user-agent: Mozilla/5.0'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/favicon.ico' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip'

curl -X GET 'https://IP/teorema505?t=1' -H 'host: IP'  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'  -H 'accept: */*'  -H 'accept-encoding: gzip' # IP: 167.172.120.3

**Comment by Valentina810** [comment]
Решение:
- подключить Spring Security и настроить:
          - обработку запросов только из "белого" списка IP
          - игнорирование любых типов запросов кроме POST
          - обрабатывать запрос только при наличии заголовка **'user-agent: MailRu-VC/1.0'**. 
При этом все входящие запросы и ответы все равно логировать

**Comment by Valentina810** [comment]
Приоритет повышен в связи с большим количеством влетающего мусора

**Comment by Valentina810** [comment]
Реализовано без SS с помощью фильтра+добавлено логирование ответа в случае успешного ответа.
Пока только фильтрация по методу POST с заголовком 'user-agent: MailRu-VC/1.0', при необходимости добавим фильтр по ip адресам

**Comment by Valentina810** [comment]
@kate-polik обновлена тестовая сборка на докерхабе

**Comment by Valentina810** [comment]
```
как это проверить?
```
ну тут по сути проблема была в том что это не откидывалось на этапе фильтрации, сейчас конечно тоже тратится ресурс на ответ, но всё же получше, например, мы не будем пытаться обработать тело пост-запроса, если у него не будет нужного нам заголовка. Закрыть это аутенфтификацией мы не можем - никаких токенов нам не выдается 😟 чтобы определить что это именно Маруся нам шлет для НАШЕГО навыка запрос 🤷‍♀️ . Можем только проверить заголовок и метод 👻
Проверяем: метод не Post, отсутствие/отличие от значения заголовка "user_agent=MailRu-VC/1.0" - да, во всех этих случаях запрос не должен пропускаться в обработку, должна валиться ошибка. Проверить вместе оба условия и по одному

**Comment by kate-polik** [comment]
> можно соап отправить

@Valentina810 получила 415 статус по аналогии с некорректным user-agent, норм?
![image](https://github.com/user-attachments/assets/e1d27b7c-e16b-4962-8c3d-122501def72b)

**Comment by Valentina810** [comment]
@kate-polik , да нормально
