### ISSUE TITLE
При возврате списка событий, в случае, если час представляет собой одну цифру (1-9) убирать ноль впереди

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/week-planner-for-marusia#84]
Например: 08:00 -> 8:00

**Comment by kate-polik** [comment]
Отрабатывает корректно, будет проверятся во всех соответствующих кейсах со временем, например,
![image](https://github.com/user-attachments/assets/8e486e82-6fae-4c57-8af0-012a190ae8a0)
![image](https://github.com/user-attachments/assets/6cc5a374-c570-4679-a8bd-15411a086ec7)
