### ISSUE TITLE
[Возможно не будет сделано] Добавить удаление события

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/week-planner-for-marusia#87]

**Comment by Valentina810** [comment]
@kate-polik тоже нужна аналитика, описать цепочку команд с максимально простым для пользователя сценарием, например: назовите день - назовите название события

**Comment by kate-polik** [comment]
@Valentina810, подскажи, пожалуйста, могу также в своей временной ветке сделать доку и загрузить ее [сюда](https://github.com/Valentina810/week-planner-for-marusia/tree/postman_jmeter_updates/src/docs) ?  или как лучше?

**Comment by Valentina810** [comment]
@kate-polik, лучше в этой https://github.com/Valentina810/week-planner-for-marusia/tree/feature/add-doc

**Comment by kate-polik** [comment]
Дублирую файл с результатом 

[\[Аналитика\] Добавить удаление события #87.pdf](https://github.com/user-attachments/files/16485373/87.pdf)

**Comment by kate-polik** [comment]
Обновленное описание 
 - [гугл-док](https://docs.google.com/document/d/1yapgW4Mx1ipY32IaiAq3fl88wYGP6n88f46dxuawKiM/edit?usp=sharing)
 - [схема в miro](https://miro.com/app/board/uXjVK5xXulw=/)
 - Залила также в ветку [/feature/add-doc](https://github.com/Valentina810/week-planner-for-marusia/tree/feature/add-doc/src/docs)

**Comment by kate-polik** [comment]
Ожидаю ответа по https://github.com/Valentina810/week-planner-for-marusia/pull/96
