### ISSUE TITLE
Обрабатывать нестандартное время при добавлении события

### ISSUE THREAD

**Issue by kate-polik** [Valentina810/week-planner-for-marusia#91]
**Варианты  нестандартного времени:**

| №| valueAction | ФР | ОР (предположительно) |
|-------------|-------------|-------------|-------------|
|1| час    | 00:00    |01:00    |
|2| минута   | 00:00    | 00:01    |
|3| девять минут  | 09:00    |00:09    |
|4| две минуты   | 02:00    | 00:02    |
|5| сорок одна минута  | 00:00    |  00:41    |
|6| шестьдесят две минуты    | 02:00    | 01:02    |
|7| шестьдесят минут   | 00:00   | 01:00   |
|8| час минута   | 00:00    | 01:01    |

**Пример запроса:**
```json
{
    "request": {
        "original_utterance": null,
        "command": "тест событие 1"
    },
    "session": {
        "user_id": "06325314",
        "session_id": "4ef31ea8-6ec0-4a20-ae83-d43d8560aea0",
        "message_id": 3
    },
    "state": {
        "session": {
            "actions": {
                "prevActions": [
                    {
                        "number": 0,
                        "valueAction": "добавь событие",
                        "operation": "ADD_EVENT"
                    },
                    {
                        "number": 1,
                        "prevOperation": "ADD_EVENT",
                        "valueAction": "воскресенье",
                        "operation": "ADD_DAY"
                    },
                    {
                        "number": 2,
                        "prevOperation": "ADD_DAY",
                        "valueAction": "две минуты", <!-- Здесь вставить значение времени -->
                        "operation": "ADD_TIME"
                    }
                ]
            }
        },
        "user": {}
    },
    "version": "1.0"
}
 ```

**Comment by Valentina810** [comment]
@kate-polik а сама не хочешь подумать, как это можно обработать? Может есть какие-то предложения?

**Comment by Valentina810** [comment]
Можно 62 минуты - 1 час и 2 минуты, шестьдесят минут - 1 час

**Comment by kate-polik** [comment]
>>Можно 62 минуты - 1 час и 2 минуты, шестьдесят минут - 1 час
да, я тоже так думала.

**Comment by Valentina810** [comment]
ага, ну тогда ко мне на очередь

**Comment by Valentina810** [comment]
Отклонено, так как в справке добавлено подробное разъяснение как называть правильно время.
"Навык \"Планировщик недели\" предоставляет возможность составления плана событий на неделю, начиная с сегодняшнего дня. Для добавления событий в расписание скажите \"Добавь событие\", далее следуйте инструкциям голосового помощника, время события нужно указывать в двадцатичетырёхчасовом формате, например девять часов, шестнадцать часов тридцать пять минут. Если вы хотите узнать план событий на сегодня скажите \"План на сегодня\". Для того чтобы узнать план на завтра, воспользуйтесь командой \"План на завтра\". Можно узнать план на всю неделю с помощью команды \"План на неделю\". Для выхода из навыка скажите \"Выход\". Версия навыка два ноль ноль"
