### ISSUE TITLE
[Версия 1.0.3] 6. Тестирование: Нагрузка (Jmeter)

### ISSUE THREAD

**Issue by kate-polik** [Valentina810/week-planner-for-marusia#92]
Основная задача https://github.com/Valentina810/week-planner-for-marusia/issues/59
-  Провести нагрузочное тестирование с помощью jmeter
-  Зафиксировать результаты в виде отчета
-  Залить проект по нагрузке в github

**Comment by Valentina810** [comment]
@kate-polik можешь также в проекте сделать папку, как для постман-коллекции

**Comment by Valentina810** [comment]
![Image](https://github.com/user-attachments/assets/5e27a0dc-3886-4dcc-8212-d8127a16fc3d)
![Image](https://github.com/user-attachments/assets/96493568-a4c6-4ed0-91f6-99d911e4ad63)

**Comment by kate-polik** [comment]
Промежуточные результаты можно посмотреть [здесь](https://github.com/Valentina810/week-planner-for-marusia/tree/postman_jmeter_updates/src/jmeter)

**Comment by Valentina810** [comment]
Отличная работа!

**Comment by Valentina810** [comment]
@kate-polik  пока предлагаю прикрыть, как все новые доработки для версии 2.0.0 сделаем перед публикацией еще раз несколько сценариев прогоним
